config/routes.rb
Rails.application.routes.draw do
  resources :areas, only: :show, param: :area_type
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  PENDING_STATE = 'pending'
  READY_STATE = 'ready'
  COMPLETE_STATE = 'complete'
  STATES = [PENDING_STATE, READY_STATE, COMPLETE_STATE].freeze

  validates :status, inclusion: { in: STATES }

  def next_status
    all_states = STATES.dup.concat(STATES)
    current_index = all_states.find_index(status)
    all_states.at(current_index + 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area_type

  def show
    filters = filters_for_type(@area_type)

    @sidebar_filter = filters[:sidebar_filter]
    @main_filter = filters[:main_filter]
  end

  private

  def filters_for_type(area_type)
    filter = {
      counter: {
        sidebar_filter: Order::PENDING_STATE,
        main_filter: Order::READY_STATE
      },
      service: {
        sidebar_filter: Order::READY_STATE,
        main_filter: Order::COMPLETE_STATE
      }
    }

    filter.fetch(area_type)
  end

  def set_area_type
    @area_type ||= params.fetch(:area_type).to_sym
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders or /orders.json
  def index
    status = params.fetch(:status, nil)
    @orders = if status.present?
                Order.where(status: params.fetch(:status))
              else
                Order.all
              end
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@order) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/area_helper.rb
module AreaHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/areas/show.html.erb
<h1>Areas#show</h1>
<p>Find me in app/views/areas/show.html.erb</p>

<p>Area Type Param <%= @area_type %></p>


<div style="display: grid; grid-template-columns: 1fr 3fr; grid-gap: 3rem">
  <aside id="sidebar_container">
    <h2>Sidebar</h2>
    <p>@sidebar_filter = <%= @sidebar_filter %></p>
    <p>Lazy load <code><%= orders_path(status: @sidebar_filter) %></code></p>

    <turbo-frame id="sidebar" src="<%= orders_path(status: @sidebar_filter) %>" style="border: 1px cornflowerblue solid">
      loading...
    </turbo-frame>
  </aside>


  <main id="main_container" >
    <h2>Main</h2>
    <p>@main_filter = <%= @main_filter %></p>
    <p>Lazy load <code><%= orders_path(status: @main_filter) %></code></p>

    <turbo-frame id="main" src="<%= orders_path(status: @main_filter) %>" style="border: 1px cornflowerblue solid">
      loading...
    </turbo-frame>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwiredPages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Order::STATES) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>
<div style="display: grid; grid-template-columns: 1fr 3fr; grid-gap: 3rem">


<turbo-frame id="sidebar" style="border: 1px cornflowerblue solid">
  <% @orders.each do |order| %>
    <turbo-frame id="<%= dom_id(order) %>" style="display: flex; justify-content: space-between; align-items: center; border: 1px crimson solid">
      <h3>
        <span>ID: <%= order.id %></span>
        <span><%= order.status %></span>
      </h3>
      <div>
        <%= link_to 'show', order_path(order), data: { "turbo-frame": :main } %>
        <%= form_for(order) do |form| %>
          <%= form.hidden_field(:status, value: order.next_status) %>
          <%= form.submit "Progress to #{order.next_status}" %>
        <% end %>
      </div>
    </turbo-frame>
  <% end %>
</turbo-frame>


<turbo-frame id="main" style="border: 1px cornflowerblue solid">
  <table>
    <thead>
    <tr>
      <th>ID</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</turbo-frame>
</div>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<turbo-frame id="main">
  <p>
    <strong>ID:</strong>
    <%= @order.id %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= @order.status %>
  </p>
</turbo-frame>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>